version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ~/.pg-data/testTask:/var/lib/postgresql/data
